[package]
name = "test-native-tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#native-tls = { version = "=0.2.11"  }
openssl = { version = "=0.10.44"  }